# Site settings
title: Math & More
email: bryan.w.bell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Writings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bjwbell.github.io" # the base hostname & protocol for your site
twitter_username: bjwbell
github_username:  bjwbell
highlighter: pygments

# Build settings
markdown: kramdown
